### ISSUE TITLE
For Other Developers

### ISSUE THREAD

**Issue by StarkGang** [Altruix/Altruix#4]
I am sorry for creating this issue, this is to reach my fellow developers, as I had no other means. I started this project called Dom Cobb, which basically detects spam messages. Inorder to test it I used my real telegram account (sent a spam btc scam message using that account to test the bot), which resulted in ban of my account and very low on karma. I created a new account afterwards and it too got banned. Now the VOIP (Voice Over Internet Protocol) number has also been banned for no reason, I suspected the issue might be caused due to an old version of owlgram client, I tried to send a premium sticker and got banned, there can be no other reason as I had no userbot connected. I sign off as a developer from project Altruix (I can do little tweaks if anyone can interact with me) as I have no Telegram account to interact with users, but you guys don't STOP! This is our years hardwork and don't waste it. Keep it maintained. Thank you for this journey but I am really fed up with telegram ignoring my mails / tweets and I don't have any other numbers for telegram. 

P.S : I want to be back but I can't. If anyone of you guys can donate a account OR help me in any case you can personally Message me on instagram - @midhun.ws
Or email me at starkgangz@gmail.com. 

Again, sorry for this mess. I am helpless.. if you guys get my message don't forget to spread the word to the developer group and altruix support group and if possible please share screenshot to the insta too. Thank you..

Instagram - midhun.ws
Email - starkgangz@gmail.com
Discord  (yet to create)

@N0BLEWOLF @anonyindian @ramanveerji @Reeshuxd @EverythingSuckz @SHRE-YANSH @Rohith-sreedharan

**Comment by anonyindian** [comment]
Send me your mobile number at anonyindian1@gmail.com @StarkGang

**Comment by StarkGang** [comment]
> Send me your mobile number at [anonyindian1@gmail.com](mailto:anonyindian1@gmail.com) @StarkGang

Done

**Comment by anonyindian** [comment]
> everyone

done
